# Generated by Django 2.0.1 on 2018-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriephoto',
            name='title',
            field=models.CharField(default='title', max_length=30),
        ),
        migrations.AlterField(
            model_name='galeriephoto',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
