# Generated by Django 2.0.1 on 2018-02-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='place',
            field=models.CharField(default='Tunis', max_length=20),
        ),
    ]
